In [1]:
import numpy as np
np.__version__

'1.26.4'

## Creating numpy arrays

1. Array from Python list
2. Array from in-built numpy functions
   - np.zeros
   - np.ones
   - np.full
   - np.empty
   - np.arange
   - np.linspace
   - np.random.randint
   - np.eye
   - np.random.random
   - np.random.normal

In [2]:
# Array from Python list
lst = [1,5,9,13]
arr = np.array(lst)
arr

array([ 1,  5,  9, 13])

In [3]:
lst1 = [3.14, 2.18, 10]
# Numpy arrays contain homogenous data, i.e. data of the same type
# Hence, it upcasts the data whenever possible
arr1 = np.array(lst1)
arr1

array([ 3.14,  2.18, 10.  ])

In [13]:
# We can specify the dtype explicitly
arr2 = np.array(lst1, dtype = int)
arr2

array([ 3,  2, 10])

In [8]:
# Multidimensional array
arr3 = np.array([range(i,i+3) for i in [2,4,6]])
arr3

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [14]:
# Creating numpy arrays from scratch

# Creating an array filled with zeros
zero = np.zeros(10, dtype=int)
zero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [15]:
zero1 = np.zeros((2,4), dtype=float)
zero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# Array filled with ones

one = np.ones((3,5), dtype=float)
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
# Array filled with a constant value

pi = np.full((2,5), 3.14)
pi

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [20]:
# Array filled with a linear sequence
arr4 = np.arange(2,20,3)
arr4

array([ 2,  5,  8, 11, 14, 17])

In [22]:
# An array of 10 values evenly spaced between 3 and 30
arr5 = np.linspace(3,30,10, dtype=int)
arr5

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [23]:
# An array of uniformly distributed random values between 0 and 1
arr6 = np.random.random((2,3))
arr6

array([[0.39489586, 0.63561958, 0.6934316 ],
       [0.04518314, 0.27689679, 0.32632825]])

In [25]:
# An array of normally distributed random values with mean = 0 and std = 1.5
arr7 = np.random.normal(0,1.5,(3,4))
arr7

array([[-0.60408571, -1.06137189, -0.49557507,  2.17087648],
       [-0.53922924,  0.99014732, -1.26125681, -0.71980448],
       [-1.08223954,  0.11879513, -0.15567502,  1.27807167]])

In [26]:
# An array of random integers in the range[5,50)
arr8 = np.random.randint(5,50,(2,5))
arr8

array([[22, 44, 13, 37, 27],
       [33, 48, 35, 16,  9]])

In [28]:
# Identity matrix
I = np.eye(4, dtype=int)
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [29]:
# An uninitialized array
arr9 = np.empty((3,4))
arr9

array([[0.60408571, 1.06137189, 0.49557507, 2.17087648],
       [0.53922924, 0.99014732, 1.26125681, 0.71980448],
       [1.08223954, 0.11879513, 0.15567502, 1.27807167]])

## Basics of Numpy arrays