In [1]:
import numpy as np
np.__version__

'1.26.4'

## Creating numpy arrays

1. Array from Python list
2. Array from in-built numpy functions
   - np.zeros
   - np.ones
   - np.full
   - np.empty
   - np.arange
   - np.linspace
   - np.random.randint
   - np.eye
   - np.random.random
   - np.random.normal

In [2]:
# Array from Python list
lst = [1,5,9,13]
arr = np.array(lst)
arr

array([ 1,  5,  9, 13])

In [3]:
lst1 = [3.14, 2.18, 10]
# Numpy arrays contain homogenous data, i.e. data of the same type
# Hence, it upcasts the data whenever possible
arr1 = np.array(lst1)
arr1

array([ 3.14,  2.18, 10.  ])

In [4]:
# We can specify the dtype explicitly
arr2 = np.array(lst1, dtype = int)
arr2

array([ 3,  2, 10])

In [5]:
# Multidimensional array
arr3 = np.array([range(i,i+3) for i in [2,4,6]])
arr3

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# Creating numpy arrays from scratch

# Creating an array filled with zeros
zero = np.zeros(10, dtype=int)
zero

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
zero1 = np.zeros((2,4), dtype=float)
zero1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
# Array filled with ones

one = np.ones((3,5), dtype=float)
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# Array filled with a constant value

pi = np.full((2,5), 3.14)
pi

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# Array filled with a linear sequence
arr4 = np.arange(2,20,3)
arr4

array([ 2,  5,  8, 11, 14, 17])

In [11]:
# An array of 10 values evenly spaced between 3 and 30
arr5 = np.linspace(3,30,10, dtype=int)
arr5

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [12]:
# An array of uniformly distributed random values between 0 and 1
arr6 = np.random.random((2,3))
arr6

array([[0.67265756, 0.39902744, 0.97790761],
       [0.1828367 , 0.13814321, 0.16912127]])

In [13]:
# An array of normally distributed random values with mean = 0 and std = 1.5
arr7 = np.random.normal(0,1.5,(3,4))
arr7

array([[ 0.12046   ,  2.13938836, -0.0221904 ,  1.14504617],
       [-0.29909645, -2.01636094, -0.11056149, -1.05210497],
       [ 2.2285807 ,  1.42818876,  1.71764278,  0.21879558]])

In [14]:
# An array of random integers in the range[5,50)
arr8 = np.random.randint(5,50,(2,5))
arr8

array([[31, 37, 25,  9, 13],
       [ 8, 28, 44, 48,  7]])

In [15]:
# Identity matrix
I = np.eye(4, dtype=int)
I

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [16]:
# An uninitialized array
arr9 = np.empty((3,4))
arr9

array([[0.12046   , 2.13938836, 0.0221904 , 1.14504617],
       [0.29909645, 2.01636094, 0.11056149, 1.05210497],
       [2.2285807 , 1.42818876, 1.71764278, 0.21879558]])

## Basics of NumPy arrays

1. Array attributes
2. Array slicing: array slices return views rather than copies of the array data
3. Reshaping of array
4. Joining arrays: `np.concatenate`, `np.hstack`, `np.vstack`, and `np.dstack`
5. Splitting arrays: `np.split`, `np.hsplit`, `np.vsplit`, and `np.dsplit`

In [17]:
np.random.seed(42)

In [18]:
x1 = np.random.randint(100, size = 6)
x2 = np.random.randint(100, size = (3,4))
x3 = np.random.randint(100, size = (3,4,5))

In [19]:
x1

array([51, 92, 14, 71, 60, 20])

In [20]:
x2

array([[82, 86, 74, 74],
       [87, 99, 23,  2],
       [21, 52,  1, 87]])

In [21]:
x3

array([[[29, 37,  1, 63, 59],
        [20, 32, 75, 57, 21],
        [88, 48, 90, 58, 41],
        [91, 59, 79, 14, 61]],

       [[61, 46, 61, 50, 54],
        [63,  2, 50,  6, 20],
        [72, 38, 17,  3, 88],
        [59, 13,  8, 89, 52]],

       [[ 1, 83, 91, 59, 70],
        [43,  7, 46, 34, 77],
        [80, 35, 49,  3,  1],
        [ 5, 53,  3, 53, 92]]])

In [23]:
# Array attributes

# 1. shape
print('Shape: ', x3.shape)

#2. ndim
print('Number of dimensions: ', x3.ndim)

#3. size
print('Size of the array: ', x3.size)

#4. dtype
print('Data type of array: ', x3.dtype)

#5. itemsize
print('Size in bytes of each element: ', x3.itemsize, 'bytes')

#6. nbytes = size*itemsize
print('Size in bytes of the array: ', x3.nbytes, 'bytes')

Shape:  (3, 4, 5)
Number of dimensions:  3
Size of the array:  60
Data type of array:  int32
Size in bytes of each element:  4 bytes
Size in bytes of the array:  240 bytes


In [25]:
# One-dimensional array slicing
x1

array([51, 92, 14, 71, 60, 20])

In [26]:
x1[::]

array([51, 92, 14, 71, 60, 20])

In [27]:
x1[::2]  # Every other element

array([51, 14, 60])

In [28]:
x1[::-1]  # Reverse array

array([20, 60, 71, 14, 92, 51])

In [29]:
x1[2: 5: 2]

array([14, 60])

In [30]:
# Multidimensional array splicing
x2

array([[82, 86, 74, 74],
       [87, 99, 23,  2],
       [21, 52,  1, 87]])

In [31]:
x2[::,::]

array([[82, 86, 74, 74],
       [87, 99, 23,  2],
       [21, 52,  1, 87]])

In [32]:
x2[::-1,::-1]

array([[87,  1, 52, 21],
       [ 2, 23, 99, 87],
       [74, 74, 86, 82]])

In [34]:
x2[:2,:3]

array([[82, 86, 74],
       [87, 99, 23]])

In [35]:
x2[:, ::2]

array([[82, 74],
       [87, 23],
       [21,  1]])

In [37]:
x2[:,1]  # Second column of the array

array([86, 99, 52])

In [38]:
x2[2]

array([21, 52,  1, 87])

In [39]:
x2[2,:]

array([21, 52,  1, 87])

In [40]:
print(x2)
x2_sub = x2[:2,:2]
print('x2_sub: \n', x2_sub)

[[82 86 74 74]
 [87 99 23  2]
 [21 52  1 87]]
x2_sub: 
 [[82 86]
 [87 99]]


In [41]:
x2_sub[1,0] = 13
print('x2_sub: \n', x2_sub)
print('x2: \n', x2)

x2_sub: 
 [[82 86]
 [13 99]]
x2: 
 [[82 86 74 74]
 [13 99 23  2]
 [21 52  1 87]]


In [42]:
# Creating copy of the array
x2_sub_copy = x2[:2,:2].copy()
x2_sub_copy[1,0] = 15
print('x2_sub_copy: \n', x2_sub_copy)
print('x2_sub: \n', x2_sub)
print('x2: \n', x2)

x2_sub_copy: 
 [[82 86]
 [15 99]]
x2_sub: 
 [[82 86]
 [13 99]]
x2: 
 [[82 86 74 74]
 [13 99 23  2]
 [21 52  1 87]]


In [44]:
# Reshape array
x = np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
x1

array([51, 92, 14, 71, 60, 20])

In [51]:
x1.reshape((6,1))

array([[51],
       [92],
       [14],
       [71],
       [60],
       [20]])

## Computations on NumPy arrays: Universal Functions

In [59]:
x = np.arange(20,40,2).reshape((2,5))
x

array([[20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [55]:
y = np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
z = np.arange(10).reshape((2,5))
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [57]:
print('x  =',x)
print('x+2=',x+2)
print('x-5=',x-5)
print('x*4=',x*4)
print('x/5=',x/5)
print('2^x=',2**x)

x  = [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]
 [33 35 37 39]]
x+2= [[ 3  5  7  9]
 [11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]
 [35 37 39 41]]
x-5= [[-4 -2  0  2]
 [ 4  6  8 10]
 [12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
x*4= [[  4  12  20  28]
 [ 36  44  52  60]
 [ 68  76  84  92]
 [100 108 116 124]
 [132 140 148 156]]
x/5= [[0.2 0.6 1.  1.4]
 [1.8 2.2 2.6 3. ]
 [3.4 3.8 4.2 4.6]
 [5.  5.4 5.8 6.2]
 [6.6 7.  7.4 7.8]]
2^x= [[          2           8          32         128]
 [        512        2048        8192       32768]
 [     131072      524288     2097152     8388608]
 [   33554432   134217728   536870912 -2147483648]
 [          0           0           0           0]]


In [61]:
print('x+z\n',np.add(x,z))
print('x-z\n',np.subtract(x,z))
print('x*z\n',np.multiply(x,z))
print('x/z\n',np.divide(x,z))

x+z
 [[20 23 26 29 32]
 [35 38 41 44 47]]
x-z
 [[20 21 22 23 24]
 [25 26 27 28 29]]
x*z
 [[  0  22  48  78 112]
 [150 192 238 288 342]]
x/z
 [[        inf 22.         12.          8.66666667  7.        ]
 [ 6.          5.33333333  4.85714286  4.5         4.22222222]]


C:\Users\Divya Tiwari\AppData\Local\Temp\ipykernel_9236\3963373118.py:4: RuntimeWarning: divide by zero encountered in divide
  print('x/z\n',np.divide(x,z))
